"""Download routes for generating and serving PDF/HTML files of resumes, cover letters, portfolios, and application history."""
from typing import Optional
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import HTMLResponse, PlainTextResponse
from sqlalchemy.orm import Session
from app.database import get_db
from app.models.user import User
from app.models.resume import Resume
from app.models.application import CoverLetter, Application
from app.models.portfolio import Portfolio
from app.routes.auth import get_current_user
from datetime import datetime

router = APIRouter(prefix="/api/downloads", tags=["Downloads"])


# --- PDF Generation Helpers (simulated) ---

def generate_resume_pdf_html(resume: Resume, user: User) -> str:
    """Generate an HTML version of the resume that can be printed as PDF."""
    skills_list = [s.strip() for s in (user.skills or "").split(",") if s.strip()]
    skills_html = "".join(f'<span class="skill">{skill}</span>' for skill in skills_list[:15])

    content = resume.parsed_content or "No content available."

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Resume - {user.full_name or user.username}</title>
    <style>
        @page {{ margin: 0.5in; }}
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: 'Segoe UI', Arial, sans-serif; color: #333; line-height: 1.6; padding: 40px; }}
        .header {{ text-align: center; margin-bottom: 30px; border-bottom: 2px solid #2563eb; padding-bottom: 20px; }}
        .header h1 {{ color: #2563eb; font-size: 28px; margin-bottom: 5px; }}
        .header p {{ color: #666; font-size: 14px; }}
        .section {{ margin-bottom: 25px; }}
        .section h2 {{ color: #2563eb; font-size: 18px; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px; margin-bottom: 15px; }}
        .skills {{ display: flex; flex-wrap: wrap; gap: 8px; margin-top: 10px; }}
        .skill {{ background: #eff6ff; color: #2563eb; padding: 4px 12px; border-radius: 12px; font-size: 13px; border: 1px solid #bfdbfe; }}
        .content {{ white-space: pre-wrap; font-size: 14px; }}
        .footer {{ text-align: center; margin-top: 40px; font-size: 12px; color: #999; border-top: 1px solid #e2e8f0; padding-top: 20px; }}
        @media print {{ body {{ padding: 0; }} .no-print {{ display: none; }} }}
    </style>
</head>
<body>
    <div class="header">
        <h1>{user.full_name or user.username}</h1>
        <p>{user.headline or ''}{' | ' if user.headline and user.location else ''}{user.location or ''}</p>
        <p>{user.email}{' | ' + user.phone if user.phone else ''}</p>
    </div>
    <div class="section">
        <h2>Professional Summary</h2>
        <p>{user.summary or 'Experienced professional with a track record of success.'}</p>
    </div>
    <div class="section">
        <h2>Skills</h2>
        <div class="skills">
            {skills_html or '<span>No skills listed</span>'}
        </div>
    </div>
    <div class="section">
        <h2>Resume Content</h2>
        <div class="content">{content}</div>
    </div>
    <div class="section">
        <h2>Experience</h2>
        <p><strong>Years of Experience:</strong> {user.experience_years or 0}</p>
        <p style="margin-top: 10px;">{user.headline or 'Professional experience'}</p>
    </div>
    <div class="footer">
        <p>Generated by AI Job Application Assistant | {datetime.utcnow().strftime('%B %d, %Y')}</p>
    </div>
</body>
</html>"""
    return html


def generate_cover_letter_pdf_html(cover_letter: CoverLetter, user: User) -> str:
    """Generate an HTML version of the cover letter that can be printed as PDF."""
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cover Letter - {user.full_name or user.username}</title>
    <style>
        @page {{ margin: 0.75in; }}
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: 'Georgia', serif; color: #333; line-height: 1.8; padding: 60px; }}
        .date {{ margin-bottom: 30px; color: #666; }}
        .salutation {{ margin-bottom: 20px; }}
        .content {{ white-space: pre-wrap; font-size: 14px; margin-bottom: 20px; }}
        .closing {{ margin-top: 30px; }}
        .signature {{ margin-top: 40px; }}
        .signature h3 {{ color: #2563eb; }}
        .footer {{ text-align: center; margin-top: 50px; font-size: 12px; color: #999; border-top: 1px solid #e2e8f0; padding-top: 20px; }}
        @media print {{ body {{ padding: 0; }} }}
    </style>
</head>
<body>
    <div class="date">
        <p>{datetime.utcnow().strftime('%B %d, %Y')}</p>
    </div>
    <div class="salutation">
        <p>Dear Hiring Manager,</p>
    </div>
    <div class="content">{cover_letter.content}</div>
    <div class="closing">
        <p>Best regards,</p>
    </div>
    <div class="signature">
        <h3>{user.full_name or user.username}</h3>
        <p>{user.email}</p>
        {f'<p>{user.phone}</p>' if user.phone else ''}
        {f'<p>{user.location}</p>' if user.location else ''}
    </div>
    <div class="footer">
        <p>Generated by AI Job Application Assistant | {datetime.utcnow().strftime('%B %d, %Y')}</p>
    </div>
</body>
</html>"""
    return html


def generate_portfolio_html_file(portfolio: Portfolio, user: User) -> str:
    """Generate the portfolio HTML."""
    if portfolio.generated_html:
        return portfolio.generated_html

    # Fallback basic portfolio
    skills_list = [s.strip() for s in (user.skills or "").split(",") if s.strip()]
    skills_html = "".join(f'<span class="skill-tag">{skill}</span>' for skill in skills_list[:10])

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{user.full_name or user.username} - Portfolio</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; }}
        header {{ background: linear-gradient(135deg, #2563eb, #1e40af); color: white; padding: 60px 20px; text-align: center; }}
        header h1 {{ font-size: 2.5em; margin-bottom: 10px; }}
        .container {{ max-width: 1000px; margin: 0 auto; padding: 20px; }}
        .section {{ padding: 40px 0; border-bottom: 1px solid #e2e8f0; }}
        .section h2 {{ color: #2563eb; margin-bottom: 20px; }}
        .skills {{ display: flex; flex-wrap: wrap; gap: 10px; }}
        .skill-tag {{ background: #2563eb; color: white; padding: 5px 15px; border-radius: 20px; font-size: 0.9em; }}
        footer {{ background: #1e40af; color: white; text-align: center; padding: 20px; margin-top: 40px; }}
    </style>
</head>
<body>
    <header>
        <h1>{user.full_name or user.username}</h1>
        <p>{user.headline or ''}</p>
    </header>
    <div class="container">
        <section class="section">
            <h2>About Me</h2>
            <p>{user.summary or f'Professional with {user.experience_years or 0} years of experience.'}</p>
        </section>
        <section class="section">
            <h2>Skills</h2>
            <div class="skills">{skills_html or '<p>No skills listed</p>'}</div>
        </section>
    </div>
    <footer>
        <p>&copy; {datetime.utcnow().year} {user.full_name or user.username}</p>
    </footer>
</body>
</html>"""
    return html


def generate_application_history_html(applications: list, user: User) -> str:
    """Generate an HTML report of application history."""
    rows = ""
    for app in applications:
        status_color = {
            "draft": "#6b7280", "submitted": "#2563eb", "reviewing": "#f59e0b",
            "interview": "#8b5cf6", "offer": "#10b981", "rejected": "#ef4444", "withdrawn": "#6b7280",
        }.get(app.status, "#6b7280")

        rows += f"""<tr>
            <td>{app.job.title if hasattr(app, 'job') and app.job else 'N/A'}</td>
            <td>{app.job.company if hasattr(app, 'job') and app.job else 'N/A'}</td>
            <td><span style="color: {status_color}; font-weight: bold;">{app.status.title()}</span></td>
            <td>{app.created_at.strftime('%Y-%m-%d') if app.created_at else 'N/A'}</td>
            <td>{app.applied_date.strftime('%Y-%m-%d') if app.applied_date else 'N/A'}</td>
        </tr>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Application History - {user.full_name or user.username}</title>
    <style>
        @page {{ margin: 0.5in; }}
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: 'Segoe UI', Arial, sans-serif; color: #333; padding: 30px; }}
        .header {{ text-align: center; margin-bottom: 30px; border-bottom: 2px solid #2563eb; padding-bottom: 15px; }}
        .header h1 {{ color: #2563eb; font-size: 24px; }}
        .header p {{ color: #666; }}
        .summary {{ display: flex; gap: 15px; margin-bottom: 25px; flex-wrap: wrap; }}
        .stat-card {{ background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 15px 20px; flex: 1; min-width: 120px; }}
        .stat-card h3 {{ font-size: 14px; color: #666; margin-bottom: 5px; }}
        .stat-card .value {{ font-size: 24px; font-weight: bold; color: #2563eb; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
        th {{ background: #2563eb; color: white; padding: 12px; text-align: left; }}
        td {{ padding: 10px 12px; border-bottom: 1px solid #e2e8f0; }}
        tr:nth-child(even) {{ background: #f8fafc; }}
        .footer {{ text-align: center; margin-top: 40px; font-size: 12px; color: #999; }}
        @media print {{ body {{ padding: 0; }} }}
    </style>
</head>
<body>
    <div class="header">
        <h1>Application History Report</h1>
        <p>{user.full_name or user.username} | {user.email}</p>
        <p>Generated on {datetime.utcnow().strftime('%B %d, %Y')}</p>
    </div>
    <div class="summary">
        <div class="stat-card"><h3>Total Applications</h3><div class="value">{len(applications)}</div></div>
        <div class="stat-card"><h3>Active</h3><div class="value">{sum(1 for a in applications if a.status in ('submitted', 'reviewing', 'interview'))}</div></div>
        <div class="stat-card"><h3>Offers</h3><div class="value">{sum(1 for a in applications if a.status == 'offer')}</div></div>
        <div class="stat-card"><h3>Rejections</h3><div class="value">{sum(1 for a in applications if a.status == 'rejected')}</div></div>
    </div>
    <table>
        <thead><tr><th>Job Title</th><th>Company</th><th>Status</th><th>Created</th><th>Applied</th></tr></thead>
        <tbody>{rows}</tbody>
    </table>
    <div class="footer">
        <p>Generated by AI Job Application Assistant</p>
    </div>
</body>
</html>"""
    return html


# --- Routes ---

@router.get("/resume/{resume_id}")
async def download_resume(
    resume_id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Generate and return a PDF download of a resume (HTML format for browser printing)."""
    resume = db.query(Resume).filter(Resume.id == resume_id).first()
    if not resume:
        raise HTTPException(status_code=404, detail="Resume not found")

    html = generate_resume_pdf_html(resume, current_user)
    return HTMLResponse(content=html)


@router.get("/cover-letter/{cover_letter_id}")
async def download_cover_letter(
    cover_letter_id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Generate and return a PDF download of a cover letter (HTML format for browser printing)."""
    cover_letter = db.query(CoverLetter).filter(
        CoverLetter.id == cover_letter_id,
        CoverLetter.user_id == current_user.id,
    ).first()
    if not cover_letter:
        raise HTTPException(status_code=404, detail="Cover letter not found")

    html = generate_cover_letter_pdf_html(cover_letter, current_user)
    return HTMLResponse(content=html)


@router.get("/portfolio")
async def download_portfolio(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Generate and return the portfolio as HTML file."""
    portfolio = db.query(Portfolio).filter(Portfolio.user_id == current_user.id).first()
    if not portfolio:
        raise HTTPException(status_code=404, detail="Portfolio not found. Generate one first.")

    html = generate_portfolio_html_file(portfolio, current_user)
    return HTMLResponse(content=html)


@router.get("/application-history")
async def download_application_history(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Generate and return application history as HTML (for PDF conversion)."""
    applications = (
        db.query(Application)
        .filter(Application.user_id == current_user.id)
        .order_by(Application.created_at.desc())
        .all()
    )

    html = generate_application_history_html(applications, current_user)
    return HTMLResponse(content=html)
